### ISSUE TITLE
Explain how the pico/nano vCPU priority works (with nice...)

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/documentation#48]

**Comment by Dekabry** [comment]
@hsablonniere  Missing words it seems ?"With nice..."  

Do you have any info on the priorities ? Otherwise i'll fetch the info somewhere.

**Comment by judu** [comment]
On Pico and Nano instances, we allow for 1 vCPU *but* we also lower the priority of the VM access to the underlying cpu.

We use the "nice" tool for that.
- Nano VMs have `nice = 5`
- Pico VMs have `nice = 10`
- All other processus have the default `nice = 1`.

The higher the `nice` value, the lower the priority. This means that when the load is high on the hypervisor, the Pico/Nano VMs slow down because they get less often access to the cpu.

**Comment by Dekabry** [comment]
Thanks Judu ! 

I'm not entirely sure we need the fine details for the customer besides: "in case of heavy load on servers, Nano & Pico have a lower access priority than other instances" ? 

Maybe add this on the pricing page ? 
We have no documentation on "Nano/Pico" also:
- create one ?  
or 
- create a section in the "scalability" page (but that's not very intuitive to find info for customers ?)

**Comment by davlgd** [comment]
> Maybe add this on the pricing page ? We have no documentation on "Nano/Pico" also:

This is already mentioned in the pricing page through a tooltip (and I don't think we want to go further on this on the public website). We can however decide to detail deeper in the technical documentation. I let you decide on this.

**Comment by Dekabry** [comment]
Hey David,

Thx ! I find that the pricing asterisk has poor readability: i didn't think of hovering and staying long enough to find the info ^^'
I'll see for that on a different issue.

I don't think adding many technical details on this is useful for the documentation readers, and even less for pricing readers. 
Regarding documentation, i think we should have a callout warning at the initial guide for creating your first app and/or scalability page.
